version: '3'

services:
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports:
      - $SERVER_PORT:3000
    volumes:
      - ./app
    depends_on:
      - mongo
    
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon server.js

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - $DB_PORT:27017
    environment:
      MONGO_INITDB_DATABASE: api-jwt
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - ./mongodb:/data/db

networks:
  app_network:
    driver: local

volumes:
  mongodb:
  node_modules: 