version: '3'

services:
  app:
    build: ./app
    container_name: node
    entrypoint: dockerize -wait tcp://mongo:27017 -timeout 30s ./entrypoint.sh
    volumes:
     - "./app:/home/node/app"
    networks:
     - jwt
    ports:
     - "3000:3000"

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: api-jwt
      MONGO_INITDB_ROOT_USERNAME: vitaopb
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongodb:/data/db
    networks:
      - jwt

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: api-jwt
      ME_CONFIG_MONGODB_AUTH_USERNAME: vitaopb
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 1234
    depends_on:
      - mongo
    networks:
      - jwt    

networks:
  jwt:
    driver: bridge
