version: '3'

services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app_network

    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon server.js

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: api-jwt
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
  node_modules: 